"""empty message

Revision ID: 6f89b4630114
Revises: 
Create Date: 2020-12-04 14:30:05.686988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f89b4630114'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('image_type', sa.String(), nullable=True),
    sa.Column('image_size', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_size_pretty', sa.String(), nullable=True),
    sa.Column('lang', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('audio', sa.String(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('audio_type', sa.String(), nullable=True),
    sa.Column('audio_duration', sa.Float(), nullable=True),
    sa.Column('audio_size', sa.Integer(), nullable=True),
    sa.Column('audio_duration_pretty', sa.String(), nullable=True),
    sa.Column('audio_size_pretty', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('logo_type', sa.String(), nullable=True),
    sa.Column('logo_size', sa.Integer(), nullable=True),
    sa.Column('logo_height', sa.Integer(), nullable=True),
    sa.Column('logo_width', sa.Integer(), nullable=True),
    sa.Column('logo_size_pretty', sa.String(), nullable=True),
    sa.Column('video', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('video_type', sa.String(), nullable=True),
    sa.Column('video_duration', sa.Float(), nullable=True),
    sa.Column('video_size', sa.Integer(), nullable=True),
    sa.Column('video_height', sa.Integer(), nullable=True),
    sa.Column('video_width', sa.String(), nullable=True),
    sa.Column('video_duration_pretty', sa.String(), nullable=True),
    sa.Column('video_size_pretty', sa.String(), nullable=True),
    sa.Column('iframe', sa.Boolean(), nullable=True),
    sa.Column('iframe_html', sa.String(), nullable=True),
    sa.Column('iframe_scripts', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content')
    # ### end Alembic commands ###
